export const ROOT_URL = 'http://localhost:3000';
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const REQUEST_REMOVE_PRODUCT = 'REQUEST_REMOVE_PRODUCT';
export const RECEIVE_REMOVE_PRODUCT = 'RECEIVE_REMOVE_PRODUCT';
export const ERROR_REMOVE_PRODUCT = 'ERROR_REMOVE_PRODUCT';

